### ISSUE TITLE
PGP signature on AUR is out of date

### ISSUE THREAD

**Issue by ghost** [xyproto/addinclude#2]
==> Verifying source file signatures with gpg...
    addinclude-1.0.1.tar.xz ... FAILED (unknown public key FCF3C8CB5CF9C8D4)
==> ERROR: One or more PGP signatures could not be verified!
Error downloading sources: addinclude

Suggest rebuilding and packaging for AUR (and maybe updating your public key).

**Comment by xyproto** [comment]
Thanks for reporting. I'm closing this issue since it's about the AUR package and not about this repository (unless I've misunderstood).
